/* 
 * API Marketplace Grupo Netshoes
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 2.0.0
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */

using System;
using System.IO;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.Reflection;
using RestSharp;
using NUnit.Framework;

using IO.Swagger.Client;
using IO.Swagger.Api;
using IO.Swagger.Model;

namespace IO.Swagger.Test
{
    /// <summary>
    ///  Class for testing PricesApi
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by Swagger Codegen.
    /// Please update the test case below to test the API endpoint.
    /// </remarks>
    [TestFixture]
    public class PricesApiTests
    {
        private PricesApi instance;

        /// <summary>
        /// Setup before each unit test
        /// </summary>
        [SetUp]
        public void Init()
        {
            instance = new PricesApi();
        }

        /// <summary>
        /// Clean up after each unit test
        /// </summary>
        [TearDown]
        public void Cleanup()
        {

        }

        /// <summary>
        /// Test an instance of PricesApi
        /// </summary>
        [Test]
        public void InstanceTest()
        {
            // TODO uncomment below to test 'IsInstanceOfType' PricesApi
            //Assert.IsInstanceOfType(typeof(PricesApi), instance, "instance is a PricesApi");
        }

        
        /// <summary>
        /// Test GetPriceProductBySku
        /// </summary>
        [Test]
        public void GetPriceProductBySkuTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //string clientId = null;
            //string accessToken = null;
            //string sku = null;
            //var response = instance.GetPriceProductBySku(clientId, accessToken, sku);
            //Assert.IsInstanceOf<InlineResponse2002> (response, "response is InlineResponse2002");
        }
        
        /// <summary>
        /// Test SavePriceProductBySku
        /// </summary>
        [Test]
        public void SavePriceProductBySkuTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //string clientId = null;
            //string accessToken = null;
            //string sku = null;
            //Body4 body = null;
            //instance.SavePriceProductBySku(clientId, accessToken, sku, body);
            
        }
        
        /// <summary>
        /// Test UpdatePriceProductBySku
        /// </summary>
        [Test]
        public void UpdatePriceProductBySkuTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //string clientId = null;
            //string accessToken = null;
            //string sku = null;
            //Body3 body = null;
            //instance.UpdatePriceProductBySku(clientId, accessToken, sku, body);
            
        }
        
    }

}
