/* 
 * API Marketplace Grupo Netshoes
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 2.0.0
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */

using System;
using System.IO;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.Reflection;
using RestSharp;
using NUnit.Framework;

using IO.Swagger.Client;
using IO.Swagger.Api;
using IO.Swagger.Model;

namespace IO.Swagger.Test
{
    /// <summary>
    ///  Class for testing StocksApi
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by Swagger Codegen.
    /// Please update the test case below to test the API endpoint.
    /// </remarks>
    [TestFixture]
    public class StocksApiTests
    {
        private StocksApi instance;

        /// <summary>
        /// Setup before each unit test
        /// </summary>
        [SetUp]
        public void Init()
        {
            instance = new StocksApi();
        }

        /// <summary>
        /// Clean up after each unit test
        /// </summary>
        [TearDown]
        public void Cleanup()
        {

        }

        /// <summary>
        /// Test an instance of StocksApi
        /// </summary>
        [Test]
        public void InstanceTest()
        {
            // TODO uncomment below to test 'IsInstanceOfType' StocksApi
            //Assert.IsInstanceOfType(typeof(StocksApi), instance, "instance is a StocksApi");
        }

        
        /// <summary>
        /// Test GetStockProductBySku
        /// </summary>
        [Test]
        public void GetStockProductBySkuTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //string clientId = null;
            //string accessToken = null;
            //string sku = null;
            //var response = instance.GetStockProductBySku(clientId, accessToken, sku);
            //Assert.IsInstanceOf<InlineResponse2003>(response, "response is InlineResponse2003");
        }
        
        /// <summary>
        /// Test SaveStockProductBySku
        /// </summary>
        [Test]
        public void SaveStockProductBySkuTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //string clientId = null;
            //string accessToken = null;
            //string sku = null;
            //Body6 body = null;
            //instance.SaveStockProductBySku(clientId, accessToken, sku, body);
            
        }
        
        /// <summary>
        /// Test UpdateStockProductBySku
        /// </summary>
        [Test]
        public void UpdateStockProductBySkuTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //string clientId = null;
            //string accessToken = null;
            //string sku = null;
            //Body5 body = null;
            //instance.UpdateStockProductBySku(clientId, accessToken, sku, body);
            
        }
        
    }

}
