/* 
 * API Marketplace Grupo Netshoes
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 2.0.0
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */


using NUnit.Framework;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using IO.Swagger.Api;
using IO.Swagger.Model;
using IO.Swagger.Client;
using System.Reflection;

namespace IO.Swagger.Test
{
    /// <summary>
    ///  Class for testing Body4
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by Swagger Codegen.
    /// Please update the test case below to test the model.
    /// </remarks>
    [TestFixture]
    public class Body4Tests
    {
        // TODO uncomment below to declare an instance variable for Body4
        //private Body4 instance;

        /// <summary>
        /// Setup before each test
        /// </summary>
        [SetUp]
        public void Init()
        {
            // TODO uncomment below to create an instance of Body4
            //instance = new Body4();
        }

        /// <summary>
        /// Clean up after each test
        /// </summary>
        [TearDown]
        public void Cleanup()
        {

        }

        /// <summary>
        /// Test an instance of Body4
        /// </summary>
        [Test]
        public void Body4InstanceTest()
        {
            // TODO uncomment below to test "IsInstanceOfType" Body4
            //Assert.IsInstanceOfType<Body4> (instance, "variable 'instance' is a Body4");
        }

        /// <summary>
        /// Test the property 'ListPrice'
        /// </summary>
        [Test]
        public void ListPriceTest()
        {
            // TODO unit test for the property 'ListPrice'
        }
        /// <summary>
        /// Test the property 'SalePrice'
        /// </summary>
        [Test]
        public void SalePriceTest()
        {
            // TODO unit test for the property 'SalePrice'
        }

    }

}
