/* 
 * API Marketplace Grupo Netshoes
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 2.0.0
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */


using NUnit.Framework;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using IO.Swagger.Api;
using IO.Swagger.Model;
using IO.Swagger.Client;
using System.Reflection;

namespace IO.Swagger.Test
{
    /// <summary>
    ///  Class for testing InlineResponse2003
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by Swagger Codegen.
    /// Please update the test case below to test the model.
    /// </remarks>
    [TestFixture]
    public class InlineResponse2003Tests
    {
        // TODO uncomment below to declare an instance variable for InlineResponse2003
        //private InlineResponse2003 instance;

        /// <summary>
        /// Setup before each test
        /// </summary>
        [SetUp]
        public void Init()
        {
            // TODO uncomment below to create an instance of InlineResponse2003
            //instance = new InlineResponse2003();
        }

        /// <summary>
        /// Clean up after each test
        /// </summary>
        [TearDown]
        public void Cleanup()
        {

        }

        /// <summary>
        /// Test an instance of InlineResponse2003
        /// </summary>
        [Test]
        public void InlineResponse2003InstanceTest()
        {
            // TODO uncomment below to test "IsInstanceOfType" InlineResponse2003
            //Assert.IsInstanceOfType<InlineResponse2003> (instance, "variable 'instance' is a InlineResponse2003");
        }

        /// <summary>
        /// Test the property 'Available'
        /// </summary>
        [Test]
        public void AvailableTest()
        {
            // TODO unit test for the property 'Available'
        }
        /// <summary>
        /// Test the property 'Links'
        /// </summary>
        [Test]
        public void LinksTest()
        {
            // TODO unit test for the property 'Links'
        }

    }

}
