/* 
 * API Marketplace Grupo Netshoes
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 2.0.0
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */


using NUnit.Framework;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using IO.Swagger.Api;
using IO.Swagger.Model;
using IO.Swagger.Client;
using System.Reflection;

namespace IO.Swagger.Test
{
    /// <summary>
    ///  Class for testing InlineResponse200ItemsImages
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by Swagger Codegen.
    /// Please update the test case below to test the model.
    /// </remarks>
    [TestFixture]
    public class InlineResponse200ItemsImagesTests
    {
        // TODO uncomment below to declare an instance variable for InlineResponse200ItemsImages
        //private InlineResponse200ItemsImages instance;

        /// <summary>
        /// Setup before each test
        /// </summary>
        [SetUp]
        public void Init()
        {
            // TODO uncomment below to create an instance of InlineResponse200ItemsImages
            //instance = new InlineResponse200ItemsImages();
        }

        /// <summary>
        /// Clean up after each test
        /// </summary>
        [TearDown]
        public void Cleanup()
        {

        }

        /// <summary>
        /// Test an instance of InlineResponse200ItemsImages
        /// </summary>
        [Test]
        public void InlineResponse200ItemsImagesInstanceTest()
        {
            // TODO uncomment below to test "IsInstanceOfType" InlineResponse200ItemsImages
            //Assert.IsInstanceOfType<InlineResponse200ItemsImages> (instance, "variable 'instance' is a InlineResponse200ItemsImages");
        }

        /// <summary>
        /// Test the property 'Url'
        /// </summary>
        [Test]
        public void UrlTest()
        {
            // TODO unit test for the property 'Url'
        }

    }

}
