/* 
 * API Marketplace Grupo Netshoes
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 2.0.0
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */


using NUnit.Framework;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using IO.Swagger.Api;
using IO.Swagger.Model;
using IO.Swagger.Client;
using System.Reflection;

namespace IO.Swagger.Test
{
    /// <summary>
    ///  Class for testing PriceResponse
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by Swagger Codegen.
    /// Please update the test case below to test the model.
    /// </remarks>
    [TestFixture]
    public class PriceResponseTests
    {
        // TODO uncomment below to declare an instance variable for PriceResponse
        //private PriceResponse instance;

        /// <summary>
        /// Setup before each test
        /// </summary>
        [SetUp]
        public void Init()
        {
            // TODO uncomment below to create an instance of PriceResponse
            //instance = new PriceResponse();
        }

        /// <summary>
        /// Clean up after each test
        /// </summary>
        [TearDown]
        public void Cleanup()
        {

        }

        /// <summary>
        /// Test an instance of PriceResponse
        /// </summary>
        [Test]
        public void PriceResponseInstanceTest()
        {
            // TODO uncomment below to test "IsInstanceOfType" PriceResponse
            //Assert.IsInstanceOfType<PriceResponse> (instance, "variable 'instance' is a PriceResponse");
        }

        /// <summary>
        /// Test the property 'ListPrice'
        /// </summary>
        [Test]
        public void ListPriceTest()
        {
            // TODO unit test for the property 'ListPrice'
        }
        /// <summary>
        /// Test the property 'SalePrice'
        /// </summary>
        [Test]
        public void SalePriceTest()
        {
            // TODO unit test for the property 'SalePrice'
        }
        /// <summary>
        /// Test the property 'Links'
        /// </summary>
        [Test]
        public void LinksTest()
        {
            // TODO unit test for the property 'Links'
        }

    }

}
